### PR TITLE
added history, mkdir, rmdir, copy commands and color change

### PR DESCRIPTION
**Pull request by hsgaurav**
and check that ash_read_line function that you made its now very short though but check for that it doesn't create any problem further

### CODE REVIEW

**Review by duskybomb — CHANGES_REQUESTED** [review]
- mkdir and rmdir functions are working but show error in shell
 - update help

**Comment by hsgaurav** [comment]
done with mkdir and rmdir functions and updated help

**Review by hsgaurav — COMMENTED** [review]
this one is the one with updated mkdir and rmdir and updated help

**Review by hsgaurav — COMMENTED** [review]
check out this one i have added ls function and copy as was earlier and removed history as it was not working properly and the one that @Eklavya42 did of mkdir was not working properly casing the programme to go for an error called segmentation fault so i just commented that

**Pull request closed without merging**
